### ISSUE TITLE
ToDo list for next release

### ISSUE THREAD

**Issue by peterw8102** [peterw8102/Z80-Retro#4]
+ [x] Reinstate the 'repeat last command' behaviour from previous releases. Lost this when the line parsing was simplified.
+ [x] Add CP/M blocking/splitting functions to the ZIOS RST 30h interface. Currently this is done in the BIOS but has a single buffer.  Delegating blocking/splitting to ZIOS allows better/more caching while reducing the size of the BIOS. Should improve SDCard write performance, especially if I ever get around to porting CP/M 3.
+ [x] Modify CP/M BIOS to use the ZIOS CP/M SDCard helpers
+ [x] Fix the checksums for the default video card font
+ [X] Fix Intel Hex checksum calculations in tools (font-editor and hex tools in the `tools` directory)
+ [x] When debugging, Ctrl-C no longer preserves the content of HL
+ [x] Look at generalising the block device I/O to allow things other than SDCards to be supported on behalf of the guest OS.
+ [x] Add a HEX file transformer to check/fix checksums and to relocate data records.
+ [x] Change build process to avoid using PHASE. Use new `hextform.js` node tools to relocated the HEX records for loading. Unfortunately PHASE doesn't work for a CSEG forcing everything in the second code page to be ASEG making locating multiple files there awkward.
+ [x] 'G' command doesn't work when NOT in debug mode and no address is specified. Should default to address 0.
+ [x] Fix bug in command line history function that can cause a random crash
+ [x] Reduce number of boot menu from 15 to 8 to restrict data to <380 bytes #5
